
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb


  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"


  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    tty: true
    volumes:
      - ./src:/src


