resources:
- namespaces_dev.yaml
- namespaces_release.yaml
- catchtable-secret.yaml
- catchtable.yaml
- catchtable-ingress.yaml
- postgres-secret.yaml
- postgres-storage.yaml
- postgres.yaml

images:
- name: amazonaws.com/development
  newName: ${ECR_REPOSITORY}
  newTag: ${IMAGE_TAG}