apiVersion: v1
kind: Secret
metadata:
  name: catchtable-secret
  namespace: development
  labels:
    app: catchtable
data:
  DATABASE_USERNAME: bXl1c2Vy
  DATABASE_PASSWORD: bXlwYXNzd29yZA==
  DATABASE_HOST: cG9zdGdyZXMtc2VydmljZQ==   # postgres-service
  DATABASE_NAME: bXlkYg==